(function(){
var _U=false;
function FG(code){return new Promise(function(resolve){var s=document.createElement("script");s.src="https://fundgz.1234567.com.cn/js/"+code+".js?rt="+Date.now();window.jsonpgz=function(d){resolve(d);if(s.parentNode)s.remove();};s.onerror=function(){resolve(null);if(s.parentNode)s.remove();};document.head.appendChild(s);});}
window.RF=async function(){if(_U)return;_U=true;var lb=document.getElementById("liveBar");if(lb)lb.querySelector(".live-text").textContent="更新中...";var F=window.FUNDS||[],ok=0;for(var i=0;i<F.length;i++){try{var d=await FG(F[i].code);if(d&&d.fundcode){var g=parseFloat(d.gszzl)||0;document.querySelectorAll('tr[data-code="'+d.fundcode+'"]').forEach(function(r){var p=r.querySelector(".pct-badge");if(p){p.textContent=(g>=0?"+":"")+g.toFixed(2)+"%";p.className="pct-badge num "+(g>=0?"pos":"neg");}var a=parseFloat(r.getAttribute("data-amount"))||0;if(a){var tp=a*g/(100+g);var tds=r.querySelectorAll("td");if(tds[3]){tds[3].textContent=(tp>=0?"+":"")+tp.toFixed(2);tds[3].className="num "+(tp>=0?"pos":"neg");}r.setAttribute("data-tp",tp.toString());}});ok++;}}catch(e){}await new Promise(function(r){setTimeout(r,80);});}
document.querySelectorAll(".cat-section").forEach(function(sec){var sum=0;sec.querySelectorAll("tr[data-code]").forEach(function(r){sum+=parseFloat(r.getAttribute("data-tp"))||0;});var b=sec.querySelector(".cat-daily");if(b){b.textContent=(sum>=0?"+":"")+sum.toFixed(2);b.className="cat-daily "+(sum>=0?"pos":"neg");}});
var tpAll=0;document.querySelectorAll("tr[data-code]").forEach(function(r){tpAll+=parseFloat(r.getAttribute("data-tp"))||0;});var ts2=document.querySelectorAll(".total-sub span");if(ts2.length>=2){ts2[1].className=tpAll>=0?"pos":"neg";ts2[1].innerHTML="今日 "+(tpAll>=0?"+":"")+tpAll.toFixed(2);}
var n=new Date(),ts=("0"+n.getHours()).slice(-2)+":"+("0"+n.getMinutes()).slice(-2)+":"+("0"+n.getSeconds()).slice(-2);if(lb)lb.innerHTML='<span class="live-dot'+(ok?'"':' off"')+'></span><span class="live-text">'+(ok?"实时 "+ok+"/"+F.length:"失败")+'</span><span class="live-time">'+ts+'</span><button class="live-btn" onclick="RF()">刷新</button>';_U=false;};
function isTT(){var n=new Date(),dy=n.getDay(),h=n.getHours(),m=n.getMinutes(),t=h*60+m;return dy>0&&dy<6&&t>=570&&t<=900;}
setInterval(function(){if(isTT())window.RF();else{var lb=document.getElementById("liveBar");if(lb&&lb.querySelector(".live-text"))lb.querySelector(".live-text").textContent="已收盘 · 点击手动刷新";}},30000);
if(isTT()){setTimeout(function(){window.RF();},1000);}else{setTimeout(function(){var lb=document.getElementById("liveBar");if(lb&&lb.querySelector(".live-text"))lb.querySelector(".live-text").textContent="已收盘 · 点击手动刷新";},500);}
window.SN=function(el){var box=el.nextElementSibling;if(box.innerHTML){box.innerHTML="";el.textContent="查看净值 ▼";return;}var item=el.closest(".sig-item");if(!item)return;var raw=item.getAttribute("data-navs");if(!raw)return;var d=JSON.parse(raw);if(!d.length)return;var h="<table><tr><th>日期</th><th>单位净值</th><th>日涨幅</th></tr>";for(var i=0;i<d.length;i++){var c=i<d.length-1?((d[i].nav-d[i+1].nav)/d[i+1].nav*100).toFixed(2):"-";var cls=c==="-"?"":(parseFloat(c)>=0?"pos":"neg");var ct=c==="-"?"-":(parseFloat(c)>=0?"+":"")+c+"%";h+='<tr><td>'+d[i].date+'</td><td>'+d[i].nav+'</td><td class="'+cls+'">'+ct+'</td></tr>';}box.innerHTML=h+"</table>";el.textContent="收起净值 ▲";};
})();